version: '3'

services:
  
  nginx:
    build: ./nginx/
    container_name: webserver
    restart: unless-stopped
    ports:
      - 443:8443
    links:
      - php
    volumes_from:
      - app-data
 
  php:
    build: ./php/
    container_name: php-container
    expose:
      - 9000
    volumes_from:
      - app-data

  app-data:
    image: php:7.0-fpm
    container_name: app-data-container
    volumes:
      - /home/ubuntu/dadcweb/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx/
      - /home/ubuntu/dadcweb/ssl:/ssl/
      - /home/ubuntu/dadcweb/wwwroot:/usr/share/nginx/html/
    command: "true"

  mysql:    
    image: mysql:5.7  
    container_name: mysql-container
    hostname: mysqldb
    expose:
      - 3306:3306  
    volumes_from:  
      - mysql-data  
    environment:  
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password  

  mysql-data:    
    image: mysql:5.7  
    container_name: mysql-data-container  
    volumes:  
      - /var/lib/mysql  
    command: "true" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
     - PMA_HOST=mysqldb
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
     - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - /custom/phpmyadmin/theme/:/www/themes/theme/   