version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 443:8443
    volumes:
      - /home/ubuntu/dadcweb/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/dadcweb/ssl:/ssl/
  