version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 443:8443
    links:
      - php
    volumes:
      - /home/ubuntu/dadcweb/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx/
      - /home/ubuntu/dadcweb/ssl:/ssl/
      - /home/ubuntu/dadcweb/wwwroot:/usr/share/nginx/html/

  php:
    image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - /home/ubuntu/dadcweb/wwwroot:/usr/share/nginx/html/
      